import math

from pygame.examples.grid import TILE_SIZE

TILESIZE = 32


ROWS = 10
COLS = 15

WINDOW_WIDTH = COLS * TILESIZE
WINDOW_HEIGHT = ROWS * TILESIZE

HALF_WINDOW_WIDTH = WINDOW_WIDTH // 2

FOV = 60 * (math.pi / 180)

RES = 4
NUM_RAYS = WINDOW_WIDTH // RES
HALF_NUM_RAYS = NUM_RAYS // 2

SCALE = WINDOW_WIDTH // NUM_RAYS

SCREEN_DIST = HALF_WINDOW_WIDTH / math.tan(FOV / 2)

DELTA_ANGLE = FOV / NUM_RAYS
PLAYER_SIZE_SCALE = TILESIZE // NUM_RAYS